# Generated by Django 4.2.20 on 2025-10-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="scripts", name="questions",),
        migrations.AddField(
            model_name="scripts",
            name="questions_sequence",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
