# Generated by Django 4.2.20 on 2025-10-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_remove_scripts_questions_scripts_questions_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="patients",
            name="cellphone",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
