# Generated by Django 4.2.20 on 2025-11-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_patients_cellphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="patients",
            name="telegram_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
